### PR TITLE
Exozodi sensitivity functions

### PR DESCRIPTION
**Pull request by douglase**
also minor corrections and a function to query Simbad for stellar parameters given a list of stellar Hipparchus identifiers.

### CODE REVIEW

**Comment by dsavransky** [comment]
Pull looks good, and thanks much for fixing all the instances of 'apparent' mag in fEZ comments.  One request before I merge: could you please update the docstring for fEZ to include the fbeta keyword input?  Internal TODO: update ICD accordingly.

**Comment by douglase** [comment]
good catch. docstring added.

**Comment by dsavransky** [comment]
Thanks.  However, I totally missed the first time that the travis results weren't being shown in the conversation (don't know why that's not working).  However, the tests did run, and they're all failing (https://travis-ci.org/github/dsavransky/EXOSIMS/jobs/741790565).  Basic issue is that HIPfromSimbad can't be imported. Most likely a dependency issue - probably need to add astroquery to the requirements and setup.  Even then, not clear if it'll pass the standard tests (although looks like it might - should try and see).

**Comment by douglase** [comment]
@dsavransky, Travis-CI is passing finally, skipping the HIPfromSimbad star catalog and function turned off fill_photometry.

**Comment by douglase** [comment]
https://travis-ci.org/github/dsavransky/EXOSIMS/builds/764165474

**Pull request merged**
